"""ActionBackend protocol — abstracts mouse/keyboard operations."""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ActionBackend(Protocol):
    """Contract for any action backend (native, dry-run, remote, etc.)."""

    def click(self, x: int, y: int, button: str = "left") -> dict: ...
    def double_click(self, x: int, y: int) -> dict: ...
    def move_to(self, x: int, y: int) -> None: ...
    def scroll(self, direction: str, amount: int, x: int | None = None, y: int | None = None) -> dict: ...
    def type_text(self, text: str) -> dict: ...
    def press_key(self, key: str) -> dict: ...
    def hotkey(self, combo: str) -> None: ...
    def screen_size(self) -> tuple[int, int]: ...
    def cursor_pos(self) -> tuple[int, int]: ...
